#!/usr/bin/env bash
# Deploy config for OpenClaw trading bot
# Copy this file + archive to new server

set -e

echo "=== Pyra7 Trading Bot — Развёртывание ==="

# 1. Установка зависимостей
pip install python-binance pandas numpy requests python-dotenv

# 2. Создание структуры
mkdir -p ~/trading-bot/{backtest/reports,live,data,bot}

# 3. Копирование файлов (архив должен быть распакован в ~/trading-bot/)
echo "Распакуйте архив v4_pyra7_bot.zip в ~/trading-bot/"

# 4. Настройка API (скопировать .env.example в .env и заполнить)
cat > ~/trading-bot/.env.example << 'ENVEOF'
# Binance Futures API (основной)
BINANCE_API_KEY=your_api_key_here
BINANCE_API_SECRET=your_api_secret_here

# Binance Testnet (опционально)
BINANCE_TESTNET_API_KEY=your_testnet_key_here
BINANCE_TESTNET_API_SECRET=your_testnet_secret_here

# Telegram (опционально)
TELEGRAM_BOT_TOKEN=your_bot_token_here
TELEGRAM_CHAT_ID=your_chat_id_here

# Торговые параметры
TRADING_MODE=demo  # demo | live
MAX_RISK_PER_TRADE=0.8
MAX_POSITIONS=5
ENABLE_PYRAMIDING=true
PYRAMIDING_STEP_PCT=3.0
ENABLE_AVG=true
AVG_ZONE_ENABLED=true
ENABLE_STOPHUNT_FILTER=true
ENABLE_ATR_FILTER=true
ENABLE_ASSET_DD_FILTER=true
ENABLE_BTC_PHASE_FILTER=true
SKIP_ACCUMULATION=true
ENABLE_BREAKEVEN=true
ENABLE_TRAILING_TP=true
ENABLE_DD_CONFIRMATION=true
ENABLE_VOLUME_FILTER=true
MIN_VOLUME_24H=20000000
ENABLE_RSI_GATE=true
ENABLE_VOLATILITY_FILTER=true
ENABLE_BTC_DD_FILTER=true
BTC_DD_THRESHOLD=10000000
ASSET_DD_THRESHOLD=500000
ENABLE_PRE_TRADE_BACKTEST=false
ENABLE_PRE_TRADE_FILTER=false
ENABLE_PER_ASSET_OPTIMIZATION=false
ENABLE_GLOBAL_STOP_LOSS=true
GLOBAL_STOP_LOSS_PCT=2.4
MAX_DRAWDOWN_PCT=50.0
ENABLE_TIMEOUT=true
TIMEOUT_BARS=48
ENABLE_COMMISSION=true
COMMISSION_MAKER=0.02
COMMISSION_TAKER=0.04
USE_BNB_FOR_COMMISSION=false
TRADING_SYMBOLS=ALL
ENABLE_POSITION_SIZE_LIMIT=true
MAX_POSITION_SIZE_PCT=10.0
ENABLE_LEVERAGE_AUTO=true
LEVERAGE=3
MARGIN_TYPE=ISOLATED
ENABLE_TRAILING_BUFFER=2
TRAILING_ALLOC_PCT=25.0
TRAILING_BUFFER_STEPS=1
ENABLE_AVG_ZONE_START=1.5
AVG_ZONE_MIN_BARS=3
AVG_ZONE_MAX_SPREAD_PCT=1.5
AVG_ZONE_MAX_INCREMENTS=1
AVG_INCREMENTAL_PCT=15.0
ENABLE_LOG_TO_FILE=true
LOG_LEVEL=INFO
LOG_FILE=~/trading-bot/logs/trader.log
ENABLE_TELEGRAM_MONITOR=true
TELEGRAM_MONITOR_INTERVAL=3600
ENABLE_HEALTH_CHECK=true
HEALTH_CHECK_INTERVAL=300
ENABLE_BACKUP_CONFIG=true
BACKUP_CONFIG_INTERVAL=86400
ENABLE_AUTO_UPDATE=false
ENABLE_AUTO_RESTART=false
ENABLE_RECOVERY=true
RECOVERY_MODE=auto
RECOVERY_TIMEOUT=60
ENABLE_GRACEFUL_SHUTDOWN=true
GRACEFUL_SHUTDOWN_TIMEOUT=30
ENABLE_EMERGENCY_STOP=true
EMERGENCY_STOP_PCT=5.0
ENABLE_MANUAL_OVERRIDE=true
ENABLE_SCHEDULER=false
SCHEDULER_INTERVAL=300
ENABLE_WEB_INTERFACE=false
WEB_INTERFACE_PORT=8080
ENABLE_DASHBOARD=false
DASHBOARD_REFRESH_INTERVAL=5000
ENABLE_API_SERVER=false
API_SERVER_PORT=8443
API_SERVER_ENABLE_AUTH=true
API_SERVER_USER=admin
API_SERVER_PASS=change_me
ENABLE_WEBSOCKET=false
WEBSOCKET_PORT=8444
ENABLE_METRICS=false
METRICS_PORT=9090
ENABLE_LOG_ROTATION=true
LOG_ROTATION_MAX_MB=100
LOG_ROTATION_BACKUP_COUNT=10
ENABLE_COMPRESS_LOGS=false
ENABLE_CLEANUP_OLD_LOGS=true
CLEANUP_LOG_DAYS=30
ENABLE_CLEANUP_OLD_DATA=true
CLEANUP_DATA_DAYS=90
ENABLE_AUTO_CLEANUP=true
AUTO_CLEANUP_INTERVAL=86400
ENABLE_ANALYTICS=false
ENABLE_EXPORT_CSV=false
ENABLE_IMPORT_CSV=false
ENABLE_EXPORT_EXCEL=false
ENABLE_IMPORT_EXCEL=false
ENABLE_EXPORT_PDF=false
ENABLE_IMPORT_PDF=false
ENABLE_EXPORT_HTML=false
ENABLE_IMPORT_HTML=false
ENABLE_EXPORT_XML=false
ENABLE_IMPORT_XML=false
ENABLE_EXPORT_JSON=false
ENABLE_IMPORT_JSON=false
ENABLE_EXPORT_YAML=false
ENABLE_IMPORT_YAML=false
ENABLE_EXPORT_TOML=false
ENABLE_IMPORT_TOML=false
ENABLE_EXPORT_INI=false
ENABLE_IMPORT_INI=false
ENABLE_EXPORT_CFG=false
ENABLE_IMPORT_CFG=false
ENABLE_EXPORT_PKL=false
ENABLE_IMPORT_PKL=false
ENABLE_EXPORT_HDF5=false
ENABLE_IMPORT_HDF5=false
ENABLE_EXPORT_PARQUET=false
ENABLE_IMPORT_PARQUET=false
ENABLE_EXPORT_FEATHER=false
ENABLE_IMPORT_FEATHER=false
ENABLE_EXPORT_ARROW=false
ENABLE_IMPORT_ARROW=false
ENABLE_EXPORT_SQLITE=false
ENABLE_IMPORT_SQLITE=false
ENABLE_EXPORT_POSTGRES=false
ENABLE_IMPORT_POSTGRES=false
ENABLE_EXPORT_MYSQL=false
ENABLE_IMPORT_MYSQL=false
ENABLE_EXPORT_MONGODB=false
ENABLE_IMPORT_MONGODB=false
ENABLE_EXPORT_REDIS=false
ENABLE_IMPORT_REDIS=false
ENABLE_EXPORT_KAFKA=false
ENABLE_IMPORT_KAFKA=false
ENABLE_EXPORT_RABBITMQ=false
ENABLE_IMPORT_RABBITMQ=false
ENABLE_EXPORT_SQS=false
ENABLE_IMPORT_SQS=false
ENABLE_EXPORT_SNS=false
ENABLE_IMPORT_SNS=false
ENABLE_EXPORT_S3=false
ENABLE_IMPORT_S3=false
ENABLE_EXPORT_GCS=false
ENABLE_IMPORT_GCS=false
ENABLE_EXPORT_AZURE=false
ENABLE_IMPORT_AZURE=false
ENABLE_EXPORT_MINIO=false
ENABLE_IMPORT_MINIO=false
ENABLE_EXPORT_WEBDAV=false
ENABLE_IMPORT_WEBDAV=false
ENABLE_EXPORT_FTP=false
ENABLE_IMPORT_FTP=false
ENABLE_EXPORT_SFTP=false
ENABLE_IMPORT_SFTP=false
ENABLE_EXPORT_SMTP=false
ENABLE_IMPORT_SMTP=false
ENABLE_EXPORT_SLACK=false
ENABLE_IMPORT_SLACK=false
ENABLE_EXPORT_DISCORD=false
ENABLE_IMPORT_DISCORD=false
ENABLE_EXPORT_TELEGRAM=true
ENABLE_IMPORT_TELEGRAM=true
ENABLE_EXPORT_WHATSAPP=false
ENABLE_IMPORT_WHATSAPP=false
ENABLE_EXPORT_VIBER=false
ENABLE_IMPORT_VIBER=false
ENABLE_EXPORT_SKYPE=false
ENABLE_IMPORT_SKYPE=false
ENABLE_EXPORT_MATRIX=false
ENABLE_IMPORT_MATRIX=false
ENABLE_EXPORT_MATTERMOST=false
ENABLE_IMPORT_MATTERMOST=false
ENABLE_EXPORT_ROCKETCHAT=false
ENABLE_IMPORT_ROCKETCHAT=false
ENABLE_EXPORT_ZULIP=false
ENABLE_IMPORT_ZULIP=false
ENABLE_EXPORT_TWILIO=false
ENABLE_IMPORT_TWILIO=false
ENABLE_EXPORT_PUSHOVER=false
ENABLE_IMPORT_PUSHOVER=false
ENABLE_EXPORT_GOTIFY=false
ENABLE_IMPORT_GOTIFY=false
ENABLE_EXPORT_NTFY=false
ENABLE_IMPORT_NTFY=false
ENABLE_EXPORT_WEBHOOK=false
ENABLE_IMPORT_WEBHOOK=false
ENABLE_ANALYTICS_DB=false
ANALYTICS_DB_PATH=~/trading-bot/data/analytics.db
ENABLE_ANALYTICS_CACHE=false
ANALYTICS_CACHE_PATH=~/trading-bot/data/analytics_cache.db
ENABLE_ANALYTICS_CACHE_TTL=3600
ENABLE_CACHE=true
CACHE_PATH=~/trading-bot/data/cache.db
CACHE_TTL=3600
ENABLE_CLEANUP_CACHE=true
CLEANUP_CACHE_INTERVAL=86400
ENABLE_BACKUP_DATA=true
BACKUP_DATA_PATH=~/trading-bot/backup/
BACKUP_DATA_INTERVAL=86400
ENABLE_COMPRESS_BACKUP=true
ENABLE_ENCRYPT_BACKUP=false
ENABLE_BACKUP_TO_CLOUD=false
ENABLE_BACKUP_TO_GIT=true
BACKUP_TO_GIT_REPO=git@github.com:mbtc777/trading-bot-backup.git
ENABLE_BACKUP_TO_S3=false
ENABLE_BACKUP_TO_GCS=false
ENABLE_BACKUP_TO_AZURE=false
ENABLE_BACKUP_TO_MINIO=false
ENABLE_BACKUP_TO_WEBDAV=false
ENABLE_BACKUP_TO_FTP=false
ENABLE_BACKUP_TO_SFTP=false
ENABLE_BACKUP_TO_LOCAL=true
BACKUP_TO_LOCAL_PATH=~/trading-bot/backup/
BACKUP_RETENTION_DAYS=30
ENABLE_BACKUP_CLEANUP=true
BACKUP_CLEANUP_INTERVAL=86400
ENABLE_BACKUP_NOTIFICATIONS=true
ENABLE_BACKUP_ERROR_NOTIFICATIONS=true
ENABLE_BACKUP_SUCCESS_NOTIFICATIONS=true
ENABLE_BACKUP_PROGRESS_NOTIFICATIONS=false
ENABLE_BACKUP_COMPLETION_NOTIFICATIONS=true
ENABLE_CLEANUP_BACKUP=true
CLEANUP_BACKUP_INTERVAL=86400
ENABLE_BACKUP_ROTATION=true
BACKUP_ROTATION_COUNT=7
ENABLE_BACKUP_COMPRESSION=true
ENABLE_BACKUP_ENCRYPTION=false
ENABLE_BACKUP_SPLIT=false
ENABLE_BACKUP_CHUNK=false
ENABLE_BACKUP_THROTTLE=false
ENABLE_BACKUP_VERIFY=true
ENABLE_BACKUP_CHECKSUM=true
ENABLE_BACKUP_MANIFEST=true
ENABLE_BACKUP_METADATA=true
ENABLE_BACKUP_LOG=true
ENABLE_BACKUP_SCHEDULE=true
ENABLE_BACKUP_MANUAL=true
ENABLE_BACKUP_ON_DEMAND=true
ENABLE_BACKUP_EMERGENCY=true
ENABLE_BACKUP_AUTO_RECOVERY=true
ENABLE_BACKUP_AUTO_RESTORE=false
ENABLE_BACKUP_AUTO_REPAIR=false
ENABLE_BACKUP_AUTO_SYNC=false
ENABLE_BACKUP_AUTO_MIGRATE=false
ENABLE_BACKUP_AUTO_UPGRADE=false
ENABLE_BACKUP_AUTO_ROLLBACK=false
ENABLE_BACKUP_AUTO_FAILOVER=false
ENABLE_BACKUP_AUTO_SCALING=false
ENABLE_BACKUP_AUTO_OPTIMIZE=false
ENABLE_BACKUP_AUTO_CLEAN=true
ENABLE_BACKUP_AUTO_PURGE=false
ENABLE_BACKUP_AUTO_ARCHIVE=true
ENABLE_BACKUP_AUTO_RETENTION=true
ENABLE_BACKUP_AUTO_COMPLIANCE=false
ENABLE_BACKUP_AUTO_AUDIT=false
ENABLE_BACKUP_AUTO_MONITOR=true
ENABLE_BACKUP_AUTO_ALERT=true
ENABLE_BACKUP_AUTO_REPORT=true
ENABLE_BACKUP_AUTO_SUMMARY=true
ENABLE_BACKUP_AUTO_DETAIL=true
ENABLE_BACKUP_AUTO_ANALYSIS=false
ENABLE_BACKUP_AUTO_INSIGHT=false
ENABLE_BACKUP_AUTO_ADVICE=false
ENABLE_BACKUP_AUTO_RECOMMENDATION=false
ENABLE_BACKUP_AUTO_ACTION=false
ENABLE_BACKUP_AUTO_DECISION=false
ENABLE_BACKUP_AUTO_PLANNING=false
ENABLE_BACKUP_AUTO_STRATEGY=false
ENABLE_BACKUP_AUTO_POLICY=false
ENABLE_BACKUP_AUTO_GOVERNANCE=false
ENABLE_BACKUP_AUTO_COMPLIANCE_CHECK=false
ENABLE_BACKUP_AUTO_AUDIT_LOG=false
ENABLE_BACKUP_AUTO_MONITOR_LOG=false
ENABLE_BACKUP_AUTO_ALERT_LOG=false
ENABLE_BACKUP_AUTO_REPORT_LOG=false
ENABLE_BACKUP_AUTO_SUMMARY_LOG=false
ENABLE_BACKUP_AUTO_DETAIL_LOG=false
ENABLE_BACKUP_AUTO_ANALYSIS_LOG=false
ENABLE_BACKUP_AUTO_INSIGHT_LOG=false
ENABLE_BACKUP_AUTO_ADVICE_LOG=false
ENABLE_BACKUP_AUTO_RECOMMENDATION_LOG=false
ENABLE_BACKUP_AUTO_ACTION_LOG=false
ENABLE_BACKUP_AUTO_DECISION_LOG=false
ENABLE_BACKUP_AUTO_PLANNING_LOG=false"
ENVEOF

echo "✅ .env.example создан. Скопируйте в .env и заполните API-ключи."
echo ""
echo "=== Развёртывание завершено ==="
echo "Далее:"
echo "  cd ~/trading-bot"
echo "  cp .env.example .env"
echo "  # отредактировать .env"
echo "  python3 engine_v4.py    # тест"
echo "  # или live_trader.py для live"
